%--------------------------------------------------------------------------
% Script for mex compilation of C++ files. Use with care. 
%
% With great power comes great responsibility.
%
% Author: BLB
% Version: 1.0
% Year: 2015
%--------------------------------------------------------------------------
% Define some paths
gslpath         = '-I/lib/gsl';
incpath         = '-I/C';
libgslpath      = 'lib/libgsl.a';
libgslcblaspath = 'lib/libgslcblas.a';

%%
% mex  -I/lib/gsl  CPPFLAGS="\$CPPFLAGS -static-libstdc++" -I∕C  ode78_qbcp.cpp   lib/libgsl.a lib/libgslcblas.a Cpp2/diffcorr.cpp Cpp2/pmcoc.cpp Cpp2/eminsem.cpp Cpp2/gnuplot_i.c Cpp2/nrutil.c Cpp2/single_orbit.cpp Cpp2/ode.cpp Cpp2/vf.cpp Cpp2/env.cpp Cpp2/FTA.cpp Cpp2/Oftsc.cpp Cpp2/Ofsc.cpp

mex(gslpath, 'ode78_qbcp.cpp', libgslpath,...
    libgslcblaspath, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');
%%
mex(gslpath, 'qbcp_vfn_novar.cpp', libgslpath,...
    libgslcblaspath, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');
%%
mex(gslpath, 'qbcp_coc.cpp', libgslpath,...
    libgslcblaspath, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');


%% Build cumovec.cpp
mex(gslpath, 'cumovec.cpp', libgslpath,... 
                            libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/eminsem.cpp',...
                          'Cpp/env.cpp');       
                      
%% Build cmic.cpp
mex(gslpath, 'cmic.cpp', libgslpath,... 
                         libgslcblaspath, ...
                         'Cpp/FTA.cpp',...
                         'Cpp/Oftsc.cpp',...
                         'Cpp/Ofsc.cpp',...
                         'Cpp/pmcoc.cpp',...
                         'Cpp/env.cpp');                    
 

%% Build cumo.cpp
mex(gslpath, 'cumo.cpp', libgslpath,... 
                          libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/env.cpp');
                      
%% Build cmo.cpp
mex(gslpath, 'cmo.cpp', libgslpath,... 
                          libgslcblaspath, ...
                          'Cpp/FTA.cpp',...
                          'Cpp/Oftsc.cpp',...
                          'Cpp/Ofsc.cpp',...
                          'Cpp/pmcoc.cpp',...
                          'Cpp/vf.cpp',...
                          'Cpp/ode.cpp',...
                          'Cpp/nrutil.c',...
                          'Cpp/single_orbit.cpp',...
                          'Cpp/env.cpp');
                      
                      

%% Build test.cpp
mex(gslpath, 'test.cpp', libgslpath,... 
                         libgslcblaspath);
                                