%--------------------------------------------------------------------------
% Script for mex compilation of C++ files. Use with care. 
% With great power comes great responsibility.
%
% Author: BLB
% Version: 2.0
% Year: 2016
%--------------------------------------------------------------------------
% Define some paths
pathlist        = {'-I/C'};
liblist         = {'lib/libgsl.a', 'lib/libgslcblas.a', 'lib/cspice.a'};

%% Build cmt_mex.cpp

%--------------------------------------------------------------------------
% Source folder
%--------------------------------------------------------------------------
srcfolder = 'Cpp';

%--------------------------------------------------------------------------
% Find all files in src folder that follows a given pattern ('*.cpp') 
%--------------------------------------------------------------------------
[~, list] = system(['find ' srcfolder ,  ' -iname "*.cpp" -o -iname "*.c"']);
srclist = regexp(list, '\n', 'split');
srclist = srclist(1:end-1);

%--------------------------------------------------------------------------
% Mex
%--------------------------------------------------------------------------
mex('mex/cmt_mex.cpp', liblist{:}, srclist{:});

%% Build cmht_mex.cpp

%--------------------------------------------------------------------------
% Source folder
%--------------------------------------------------------------------------
srcfolder = 'Cpp';

%--------------------------------------------------------------------------
% Find all files in src folder that follows a given pattern ('*.cpp') 
%--------------------------------------------------------------------------
[~, list] = system(['find ' srcfolder ,  ' -iname "*.cpp" -o -iname "*.c"']);
srclist = regexp(list, '\n', 'split');
srclist = srclist(1:end-1);

%--------------------------------------------------------------------------
% Mex
%--------------------------------------------------------------------------
mex('mex/cmht_mex.cpp', liblist{:}, srclist{:});


%% Build cmhtp_mex.cpp

%--------------------------------------------------------------------------
% Source folder
%--------------------------------------------------------------------------
srcfolder = 'Cpp';

%--------------------------------------------------------------------------
% Find all files in src folder that follows a given pattern ('*.cpp') 
%--------------------------------------------------------------------------
[~, list] = system(['find ' srcfolder ,  ' -iname "*.cpp" -o -iname "*.c"']);
srclist = regexp(list, '\n', 'split');
srclist = srclist(1:end-1);

%--------------------------------------------------------------------------
% Mex
%--------------------------------------------------------------------------
mex('mex/cmhtp_mex.cpp', liblist{:}, srclist{:});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%              DEPRECATED AFTER THIS POINT                            %%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
return

%%
% mex  -I/lib/gsl  CPPFLAGS="\$CPPFLAGS -static-libstdc++" -I∕C  ode78_qbcp.cpp   lib/libgsl.a lib/libgslcblas.a Cpp2/diffcorr.cpp Cpp2/pmcoc.cpp Cpp2/eminsem.cpp Cpp2/gnuplot_i.c Cpp2/nrutil.c Cpp2/single_orbit.cpp Cpp2/ode.cpp Cpp2/vf.cpp Cpp2/env.cpp Cpp2/FTA.cpp Cpp2/Oftsc.cpp Cpp2/Ofsc.cpp

mex('ode78_qbcp.cpp', liblist{:}, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');

%%
mex(gslpath, 'qbcp_vfn_novar.cpp', liblist{:}, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');

%%
mex(gslpath, 'qbcp_coc.cpp', liblist{:}, ...
    'Cpp2/FTA.cpp',...
    'Cpp2/Oftsc.cpp',...
    'Cpp2/Ofsc.cpp',...
    'Cpp2/pmcoc.cpp',...
    'Cpp2/vf.cpp',...
    'Cpp2/ode.cpp',...
    'Cpp2/nrutil.c',...
    'Cpp2/single_orbit.cpp',...
    'Cpp2/eminsem.cpp',...
    'Cpp2/env.cpp');


%% Build cumovec.cpp
mex(gslpath, 'cumovec.cpp', liblist{:}, ...
                            'Cpp/FTA.cpp',...
                            'Cpp/Oftsc.cpp',...
                            'Cpp/Ofsc.cpp',...
                            'Cpp/pmcoc.cpp',...
                            'Cpp/vf.cpp',...
                            'Cpp/ode.cpp',...
                            'Cpp/nrutil.c',...
                            'Cpp/single_orbit.cpp',...
                            'Cpp/eminsem.cpp',...
                            'Cpp/env.cpp');       
                      
%% Build cmic.cpp
mex(gslpath, 'cmic.cpp', liblist{:}, ...
                         'Cpp/FTA.cpp',...
                         'Cpp/Oftsc.cpp',...
                         'Cpp/Ofsc.cpp',...
                         'Cpp/pmcoc.cpp',...
                         'Cpp/env.cpp');                    
 

%% Build cumo.cpp
mex(gslpath, 'cumo.cpp', liblist{:}, ...
                         'Cpp/FTA.cpp',...
                         'Cpp/Oftsc.cpp',...
                         'Cpp/Ofsc.cpp',...
                         'Cpp/pmcoc.cpp',...
                         'Cpp/vf.cpp',...
                         'Cpp/ode.cpp',...
                         'Cpp/nrutil.c',...
                         'Cpp/single_orbit.cpp',...
                         'Cpp/env.cpp');
                      
%% Build cmo.cpp
mex(gslpath, 'mex/cmo.cpp', liblist{:}, ...
                            'Cpp/FTA.cpp',...
                            'Cpp/Oftsc.cpp',...
                            'Cpp/Ofsc.cpp',...
                            'Cpp/pmcoc.cpp',...
                            'Cpp/vf.cpp',...
                            'Cpp/ode.cpp',...
                            'Cpp/nrutil.c',...
                            'Cpp/single_orbit.cpp',...
                            'Cpp/env.cpp');
                    
%% Build test.cpp
mex(gslpath, 'test.cpp', liblist{:});
                                