Description of rotation
Home > Toolbox > rotation.m
rotation
PURPOSE
SYNOPSIS
function XYZrot = rotation(XYZ,P)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SpiralOrbit
arrow3
rotateSurf
SOURCE CODE
function XYZrot = rotation(XYZ,P)
XYZrot = XYZ;
for i =1:size(XYZ,1)
    XYZrot(i,:) = (P*XYZrot(i,:)')';
end