Description of flight_path_angle
Home > computation > flight_path_angle.m
flight_path_angle
PURPOSE
-------------------------------------------------------------------------%
SYNOPSIS
function fpa = flight_path_angle(yvc, center)
DESCRIPTION
-------------------------------------------------------------------------%
 flight_path_angle(yvc, center)
 Flight path angle in radian. If the state in position/velocity is (x, v),
 the sinus of the flight path angle with respect to the center x0
 is given by:
   sin(fpa)  = - (x - xO).v / (|x - x0|*|v|)
 Author: BLB
 Version: 1.0
 Year: 2015
-------------------------------------------------------------------------%
 Position wrt object's center
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
blt -------------------------------------------------------------------------%
earth2manifold -------------------------------------------------------------------------%
lfb -------------------------------------------------------------------------%
lfb_eml1 -------------------------------------------------------------------------%
SOURCE CODE
%-------------------------------------------------------------------------%
% flight_path_angle(yvc, center)
%
% Flight path angle in radian. If the state in position/velocity is (x, v),
% the sinus of the flight path angle with respect to the center x0
% is given by:
%
%   sin(fpa)  = - (x - xO).v / (|x - x0|*|v|)
%
% Author: BLB
% Version: 1.0
% Year: 2015
%-------------------------------------------------------------------------%
function fpa = flight_path_angle(yvc, center)
    % Position wrt object's center
    erl = yvc(1:3) - center';
    %Calcul du sinus
    sinfpal = -  erl' * yvc(4:6)/ (norm(erl) * norm(yvc(4:6)));
    fpa = asin(sinfpal);
end