%--------------------------------------------------------------------------
% Script for mex compilation of the C++ cumo.cpp. For now, only MATLAB R2013a
% is compiling this file, because the <complex.h> header is not recognized
% using MATLAB R2015b.
%
% Author: BLB
% Year: 09/2016
%--------------------------------------------------------------------------
% Define some paths
gslpath         = '-I/lib/gsl';
incpath         = '-I/C';
libgslpath      = 'lib/libgsl.a';
libgslcblaspath = 'lib/libgslcblas.a';

%% Build cumo.cpp: mex as a function
mex(gslpath, 'mex/cumo.cpp', libgslpath,... 
                             libgslcblaspath, ...
                            'Cpp/FTA.cpp',...
                            'Cpp/Oftsc.cpp',...
                            'Cpp/Ofsc.cpp',...
                            'Cpp/pmcoc.cpp',...
                            'Cpp/vf.cpp',...
                            'Cpp/ode.cpp',...
                            'Cpp/nrutil.c',...
                            'Cpp/single_orbit.cpp',...
                            'Cpp/env.cpp');